import type { Place, Trip, Home, CuratedList, TimelineItem } from '@/types/shared';
import type { FriendsNetwork, UserProfile } from './api-hooks';

export const mockPlaces: Place[] = [
  {
    id: 'place-lisbon-01',
    name: 'Atlas Rooftop Bar',
    city: 'Lisbon',
    country: 'Portugal',
    category: 'nightlife',
    note: 'Sunset cocktails with a panoramic view over the Tagus.',
    organized: true,
    context: 'trip',
    tripName: 'Lisbon Getaway',
    homeYears: undefined,
    lists: ['favorites'],
  },
  {
    id: 'place-nyc-02',
    name: 'Stumptown Coffee',
    city: 'New York',
    country: 'USA',
    category: 'coffee',
    note: 'Grab a flat white before wandering the West Village.',
    organized: false,
    context: 'home',
    tripName: undefined,
    homeYears: '2016-2020',
    lists: ['coffee'],
  },
  {
    id: 'place-kyoto-03',
    name: 'Nishiki Market Bites',
    city: 'Kyoto',
    country: 'Japan',
    category: 'restaurant',
    note: 'Street-food crawl with matcha taiyaki.',
    organized: true,
    context: 'trip',
    tripName: 'Kyoto Autumn',
    homeYears: undefined,
    lists: ['wish-list'],
  },
];

export const mockTrips: Trip[] = [
  {
    id: 'trip-lisbon',
    name: 'Lisbon Getaway',
    city: 'Lisbon',
    country: 'Portugal',
    flag: '🇵🇹',
    imageUrl: 'https://images.unsplash.com/photo-1464790719320-516ecd75af6c?auto=format&fit=crop&w=800&q=60',
    heroImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=60',
    startDate: new Date('2024-04-04'),
    endDate: new Date('2024-04-10'),
    collaborators: [],
    isPast: false,
    tips: 'Book a sunset sail on the Tagus.',
    photos: [],
    description: 'Slow mornings, pastel de nata afternoons, and miradouros every evening.',
    places: [
      { id: 'place-lisbon-01', name: 'Atlas Rooftop Bar' },
      { id: 'place-lisbon-02', name: 'Time Out Market' },
    ],
  },
  {
    id: 'trip-kyoto',
    name: 'Kyoto Autumn',
    city: 'Kyoto',
    country: 'Japan',
    flag: '🇯🇵',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60',
    heroImage: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=60',
    startDate: new Date('2023-11-02'),
    endDate: new Date('2023-11-12'),
    collaborators: [],
    isPast: true,
    tips: 'Reserve tea ceremony slots near Gion.',
    photos: [],
    description: 'Maple leaves, temple bells, and ramen between shrine visits.',
    places: [{ id: 'place-kyoto-03', name: 'Nishiki Market Bites' }],
  },
];

export const mockHomes: Home[] = [
  {
    id: 'home-nyc',
    city: 'New York',
    country: 'USA',
    adminDivision: 'New York',
    adminDivisionCode: 'NY',
    countryCode: 'US',
    latitude: 40.7128,
    longitude: -74.006,
    startDate: '2016-01-01',
    endDate: '2020-12-31',
    status: 'past',
    userId: 'mock-user',
    createdAt: '2015-12-01',
    updatedAt: '2020-12-31',
    tips: 'Morning jogs on the Hudson Greenway.',
    favorites: ['place-nyc-02'],
  },
  {
    id: 'home-lisbon',
    city: 'Lisbon',
    country: 'Portugal',
    adminDivision: 'Lisboa',
    adminDivisionCode: 'LX',
    countryCode: 'PT',
    latitude: 38.7223,
    longitude: -9.1393,
    startDate: '2021-02-01',
    endDate: undefined,
    status: 'current',
    userId: 'mock-user',
    createdAt: '2021-02-02',
    updatedAt: '2024-02-01',
    tips: 'Ride the 28E tram early to skip the crowds.',
    favorites: ['place-lisbon-01'],
  },
];

export const mockLists: CuratedList[] = [
  {
    id: 'favorites',
    name: 'Weekend Favorites',
    emoji: '✨',
    description: 'Go-to spots when friends are in town.',
    color: 'amber',
    userId: 'mock-user',
  },
  {
    id: 'coffee',
    name: 'Cafe Crawl',
    emoji: '☕️',
    description: 'Third-wave hits across the globe.',
    color: 'teal',
    userId: 'mock-user',
  },
];

export const mockFriendsNetwork: FriendsNetwork = {
  friends: [
    {
      id: 'friend-1',
      userId: 'amelia',
      name: 'Amelia Rivers',
      avatarUrl: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=200&q=60',
      friendsSince: '2022-05-10',
      placeCount: 8,
    },
    {
      id: 'friend-2',
      userId: 'mateo',
      name: 'Mateo Silva',
      avatarUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=200&q=60',
      friendsSince: '2021-09-04',
      placeCount: 5,
    },
  ],
  cities: [
    {
      city: 'Barcelona',
      country: 'Spain',
      friends: [
        {
          userId: 'amelia',
          name: 'Amelia Rivers',
          avatarUrl: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=200&q=60',
          placeCount: 4,
        },
      ],
      places: [
        {
          id: 'place-bcn-01',
          name: 'El Xampanyet',
          category: 'restaurant',
          friendId: 'amelia',
          friendName: 'Amelia Rivers',
        },
      ],
      totalPlaces: 4,
    },
    {
      city: 'Mexico City',
      country: 'Mexico',
      friends: [
        {
          userId: 'mateo',
          name: 'Mateo Silva',
          avatarUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=200&q=60',
          placeCount: 5,
        },
      ],
      places: [
        {
          id: 'place-cdmx-01',
          name: 'Contramar',
          category: 'restaurant',
          friendId: 'mateo',
          friendName: 'Mateo Silva',
        },
      ],
      totalPlaces: 5,
    },
  ],
  totalPlaces: 13,
  totalCities: 2,
};

export const mockTimelineItems: TimelineItem[] = [
  {
    type: 'trip',
    id: 'trip-lisbon',
    name: 'Lisbon Getaway',
    location: 'Lisbon, Portugal',
    city: 'Lisbon',
    country: 'Portugal',
    startDate: '2024-04-04',
    endDate: '2024-04-10',
    isCurrent: false,
    isPast: false,
    placeCounts: { visited: 5, endorsed: 2, toVisit: 3 },
    completionPercentage: 45,
  },
  {
    type: 'home',
    id: 'home-lisbon',
    name: 'Lisbon, Portugal',
    location: 'Lisbon, Portugal',
    city: 'Lisbon',
    country: 'Portugal',
    startDate: '2021-02-01',
    endDate: undefined,
    isCurrent: true,
    isPast: false,
    placeCounts: { localFavorites: 6 },
    completionPercentage: 80,
  },
  {
    type: 'trip',
    id: 'trip-kyoto',
    name: 'Kyoto Autumn',
    location: 'Kyoto, Japan',
    city: 'Kyoto',
    country: 'Japan',
    startDate: '2023-11-02',
    endDate: '2023-11-12',
    isCurrent: false,
    isPast: true,
    placeCounts: { visited: 7, endorsed: 4, toVisit: 2 },
    completionPercentage: 100,
  },
];

export const mockUserProfile: UserProfile = {
  id: 'mock-user',
  email: 'traveler@galligo.app',
  display_name: 'Galli Traveler',
  avatar_url: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=200&q=60',
  bio: 'From Lisbon rooftops to Kyoto alleyways—curating joy in every city.',
};
